services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pmd_failure_bot'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
